directories:
  output: dist
  buildResources: build
appId: dev.gshadow.gshell
productName: gshell
executableName: gsh
mac:
  icon: icon.png
  target:
    - dmg
    - zip
  publish:
    - provider: generic
      url: https://github.com/GShadow-Dev/gshell/releases/latest
win:
  icon: icon.png
  target:
    - nsis
  publish:
    - provider: generic
      url: https://github.com/GShadow-Dev/gshell/releases/latest
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
linux:
  icon: icon.png
  target:
    - deb
    - appImage
  mimeTypes:
    - application/x-myapp
  publish:
    - provider: generic
      url: https://github.com/GShadow-Dev/gshell/releases/latest
files: []
electronVersion: 23.1.3
